### PR TITLE
ID review

### PR DESCRIPTION
**Pull request by dmuelle**

### CODE REVIEW

**Comment by dmuelle** [comment]
The guide looks good- in addition to the minor ID edits proposed in this PR, i had one question:

In the Deploying the microservices section, after the `Create the kubernetes.yaml file.` tab, it says

> The `image` is the name and tag of the container image that you want to use for the container. The image address is the OCR address that you logged in to.

Is this an informational statement, or is it asking the user to substitute values after they create the file from the example? IE does the user have to edit the yaml file or just create it?

**Comment by AustinSeto** [comment]
@dmuelle the `image` referenced is informational. The user should be able to create the `kubernetes.yaml` file as displayed in the guide.

**Review by AustinSeto — APPROVED** [review]
LGTM

I'm fine to merge this if there's no problem with the part about creating the `kubernetes.yaml` file.

**Comment by dmuelle** [comment]
I think it could be a little more clear that the user doesnt need to edit the file- I made a slight edit at that line

**Review by gkwan-ibm — APPROVED** [review]

**Pull request merged**
